# Generated by Django 4.2 on 2026-06-04 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('PASSWORD_CHANGED', 'Password Changed'), ('ATTENDANCE_MARKED', 'Attendance Marked'), ('ATTENDANCE_REJECTED', 'Attendance Rejected'), ('ATTENDANCE_MODIFIED', 'Attendance Modified'), ('SESSION_STARTED', 'Session Started'), ('SESSION_ENDED', 'Session Ended'), ('QR_GENERATED', 'QR Code Generated'), ('USER_CREATED', 'User Created'), ('USER_MODIFIED', 'User Modified'), ('USER_DEACTIVATED', 'User Deactivated'), ('COURSE_CREATED', 'Course Created'), ('ENROLLMENT_CREATED', 'Student Enrolled'), ('EXPORT_GENERATED', 'Report Exported')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'event_type'], name='audit_logs_user_id_b5ee1c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='audit_logs_event_t_1d94d4_idx'),
        ),
    ]
